---
title: "Homework part 1 solution"
author: "Willem Vervoort"
date: "4 July 2018"
output: pdf_document
---

Solutions for fitting the Paso Roldan data

First set the working directory, load packages and load the data

```{r}
setwd("C:/Users/rver4657/Dropbox (Sydney Uni)/IMFIA_course_July2018")

require(tidyverse)
require(hydromad)

load("data/PasoRoldan.Rdata")
```

Select a window of 6 or 7 years to calibrate the model

```{r}
Data_cal <- window(PasoRoldan, start="1998-01-01",
                   end = "2003-12-31")
```

Define the model with ranges of parameters, just following the Cotter example:

```{r}
PRMod <- hydromad(Data_cal, sma="gr4j",
                 routing="gr4jrouting",
                 etmult=c(0.05,0.5),
                 x1 = c(100,1500), x2 = c(-30,20),
                 x3 =c(5,500), x4 = c(0.5,10))

```

Then use fitByOptim() to fit the model

```{r}
PasoRFit <- fitByOptim(PRMod,
  objective=~hmadstat("r.sq.sqrt")(Q,X),
  samples=1000,method="PORT")
summary(PasoRFit)
```
Check the coefficients
```{r}
coef(PasoRFit)
```
As we predicted, x1 would be much smaller. 

And make a plot
```{r}
xyplot(PasoRFit)
```

